DATA part1;
 INFILE 'C:/Users/LEEEUNJIN/Desktop/2018-1/대학원/이론통계학1/6주차/part1.txt';
 INPUT NO Y Year R1-R24;
RUN;


PROC LOGISTIC DATA=part1; 
  MODEL Y = R1-R24 / SELECTION=BACKWARD ;
RUN;

PROC GENMOD DATA=part1 DESCENDING; 
  MODEL Y = R5 R6 R16 R18 / DIST=BINOMIAL LINK=LOGIT   ;
RUN;
